services:
  latex:
     build: .
     container_name: pdflatex
     volumes:
       - .:/sources
     working_dir: /sources
     command: sh -c "make realclean && make paval && chmod +x /sources/paval && echo '' | pdflatex --shell-escape Memoria.tex && rm paval Memoria-* Memoria.gnuploterrors *.aux *.log && make realclean"